In [ ]:
#question 1
name = "Arulmozhiarasu"
age = "19"

print("Name:", name)
print("Age:", age)


Name: Arulmozhiarasu
Age: 19


In [ ]:
#question 2
X = "Datascience is used to extract meaningful insights."
split_string = X.split()

print(split_string)


['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [ ]:
#question 3
def mul_Num(a,b):
    multiply=a*b;
    return multiply
    
num1=25  
num2=55
print(mul_Num(num1,num2))

50


In [ ]:
#question 4
states_capitals = {
    "Tamilnadu": "Chennai",
    "Karnataka": "Bengaluru",
    "Kerala": "Thiruvanandhapuram",
    "Andhra Pradesh": "Amaravati",
    "Telangana": "Hyderabad"
}


print("States:")
for state in states_capitals.keys():
    print(state)


print("\nCapitals:")
for capital in states_capitals.values():
    print(capital)


States:
Tamilnadu
Karnataka
Kerala
Andhra Pradesh
Telangana

Capitals:
Chennai
Bengaluru
Thiruvanandhapuram
Amaravati
Hyderabad


In [ ]:
#question 5
numbers = list(range(1, 1001))
print(numbers[:10])  


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#question 6 
import numpy as np

identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#question 7 
import numpy as np
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#question 8 
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = array1 + array2
print(result)



[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [ ]:
#question 9 
import numpy as np
import datetime
start_date = datetime.date(2023, 2, 1)
end_date = datetime.date(2023, 3, 1)
date_range = np.arange(start_date, end_date + datetime.timedelta(days=1), dtype='datetime64[D]')
for date in date_range:
    print(date)


2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


In [ ]:
#question 10
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)


     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
